### ISSUE TITLE
Unable to run the code in single GPU

### ISSUE THREAD

**Issue by HaihangWu** [OpenGVLab/UniFormerV2#11]
Hi author:
    When I try to run the code in a single GPU, it reports "Default process group has not been initialized, please make sure to call init_process_group". I add the command dist.init_process_group("nccl", init_method=str(init_method), rank=1, world_size=1) in misc.py file, but I get the same error. I create  conda virtual environment following your software installation instruction, and  I can run my own code in both single GPU and multiple GPUs within this environment. Could you help have a look at it? Following is more error info:
Traceback (most recent call last):
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/tools/run_net_multi_node.py", line 69, in <module>
    main()
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/tools/run_net_multi_node.py", line 50, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/slowfast/utils/misc.py", line 312, in launch_job
    func(cfg=cfg)
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/tools/train_net.py", line 431, in train
    train_loader = loader.construct_loader(cfg, "train")
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/slowfast/datasets/loader.py", line 147, in construct_loader
    sampler = utils.create_sampler(dataset, shuffle, cfg)
  File "/data/gpfs/projects/punim0512/Haihangw-Projects/video_train/Uniformer/slowfast/datasets/utils.py", line 412, in create_sampler
    sampler = DistributedSampler(dataset) if cfg.NUM_GPUS >= 1 else None
  File "/data/gpfs/projects/punim0512/haihang_envs/Uniformerv2/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    num_replicas = dist.get_world_size()
  File "/data/gpfs/projects/punim0512/haihang_envs/Uniformerv2/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1067, in get_world_size
    return _get_group_size(group)
  File "/data/gpfs/projects/punim0512/haihang_envs/Uniformerv2/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 453, in _get_group_size
    default_pg = _get_default_group()
  File "/data/gpfs/projects/punim0512/haihang_envs/Uniformerv2/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 584, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
srun: error: spartan-gpgpu072: task 0: Exited with exit code 1

**Comment by Andy1621** [comment]
As there is no more activity, I am closing the issue, don't hesitate to reopen it if necessary.
